apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
      - name: flask-webapp
        image: aseemfaras/flask-webapp
        ports:
        - containerPort: 5000
--- 
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-webapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31234  # Must be in range 30000-32767
